<div class="row">
    <div class="col-11 offset-1">
        <h3>Resumé</h3>

        <div class="document-gallery-form-messages"></div>

        <div id="upload-document-zone" style="width: 100%; min-height: 100px;" class=""></div>

        <div id="documents-gallery" class="row"></div>

    </div>
</div>

<!-- div class="row hide">
    <div class="col-11 offset-1">

        <hr />

        <h4>Resumé (Optional)</h4>

        <form id="AOFormResume" name="AOFormResume" class="" data-service="AOServiceResume">

            <div class="form-messages"></div>

            <div id="resume-container" class="form-group">
                <div id="resume" name="resume"></div>
                <div class="message-container"></div>
            </div>

            <div class="form-group right">
                <button type="button" id="resume-save" class="btn btn-md theme-background"><i class="icon-save"></i>&nbsp; Save</button>
            </div>

        </form>
    </div>
</div -->

<!-- Document Display Template -->
<div id="document-template" class="hide">
    <div class="image-container col-4 animated fadeIn">
        <div class="options-container fx-item-zoom-in">

            <img class="img-fluid options-item" src="" alt="" title="" id="" />

            <div class="options-overlay bg-black-75">
                <div class="options-overlay-content">

                    <h4 class="caption-title">Set Title</h4>
                    <h5 class="description">Set Description</h5>

                    <button type="button" class="btn btn-sm btn-primary img-lightbox">
                        <i class="icon-eye mr-1"></i> View
                    </button>
                    <button type="button" class="btn btn-sm btn-primary img-edit">
                        <i class="icon-pencil mr-1"></i> Edit
                    </button>
                    <button type="button" class="btn btn-sm btn-primary img-copy" data-title="Copied" data-clipboard-text="">
                        <i class="icon-copy mr-1"></i> Copy Link
                    </button>
                    <button type="button" class="btn btn-sm btn-danger mt-1 img-delete">
                        <i class="icon-trash mr-1"></i> Remove
                    </button>

                </div>
            </div>

        </div>
    </div>
</div>
<!-- END Document Display Template -->
