<header id="header" class="full-header">
    <div id="header-wrap">
        <div class="container">
            <div class="header-row">

                <!-- Logo
                ============================================= -->
                <div id="logo">
                    <a href="<?php echo AOAdmin::get_current_admin_url(); ?>" class="standard-logo"
                       data-light-logo="<?php echo plugins_url( 'ao-admin/assets/images/3ao-logo.png'); ?>"
                       data-dark-logo="<?php echo plugins_url( 'ao-admin/assets/images/3ao-logo-dark.png'); ?>">
                        <img src="<?php echo plugins_url( 'ao-admin/assets/images/3ao-logo.png' ); ?>" alt="3AO Logo"></a>
                    <a href="<?php echo AOAdmin::get_current_admin_url(); ?>" class="retina-logo"
                       data-light-logo="<?php echo plugins_url( 'ao-admin/assets/images/3ao-logo@2x.png'); ?>"
                       data-dark-logo="<?php echo plugins_url( 'ao-admin/assets/images/3ao-logo-dark@2x.png'); ?>">
                        <img src="<?php echo plugins_url( 'ao-admin/assets/images/3ao-logo@2x.png') ?>" alt="3AO Logo"></a>
                </div>
                <!-- #logo end -->

                <div class="header-misc">

                    <!-- Top Theme Controls
                    ============================================= -->
                    <div class="row header-misc-icon">

                        <!-- Theme Style (light or dark) -->
                        <div class="col-md-7 form-group mt-4">
                            <div class="btn-group">
                                <input type="radio" class="btn-check" name="theme-style" id="theme-style-light" checked="" autocomplete="off" value="">
                                <label for="theme-style-light" class="btn btn-outline-secondary px-3 fw-semibold ls0 nott">Light</label>
                                <input type="radio" class="btn-check" name="theme-style" id="theme-style-dark" autocomplete="off" value="dark">
                                <label for="theme-style-dark" class="btn btn-outline-secondary px-3 fw-semibold ls0 nott">Dark</label>
                            </div>
                        </div>

                        <!-- Theme Color (Highlight Color Picker) -->
                        <div class="col-md-5 form-group mt-4">
                            <button id="js-colorpicker" class="btn btn-outline-secondary">Color</button>
                        </div>

                    </div>
                    <!-- #top-search end -->

                </div>

                <div id="primary-menu-trigger">
                    <svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
                </div>

                <!-- Primary Navigation
                ============================================= -->
                <?php echo AOAdmin::view('navigation'); ?>
                <!-- #primary-menu end -->

            </div>
        </div>
    </div>
    <div class="header-wrap-clone"></div>
</header>