<div class="row">
    <div class="col-11 offset-1">

        <h3>Images</h3>

        <div class="gallery-form-messages"></div>

        <div id="upload-zone" style="width: 100%; min-height: 100px;" class=""></div>

        <div id="gallery" class="row"></div>

    </div>
</div>

<!-- Gallery Image Template -->
<div id="gallery-template" class="hide">
    <div class="image-container col-4 animated fadeIn">
        <div class="options-container fx-item-zoom-in">

            <img class="img-fluid options-item" src="" alt="" title="" id="" />

            <div class="options-overlay bg-black-75">
                <div class="options-overlay-content">

                    <h4 class="caption-title">Set Title</h4>
                    <h5 class="description">Set Description</h5>

                    <button type="button" class="btn btn-sm btn-primary img-lightbox">
                        <i class="icon-eye mr-1"></i> View
                    </button>
                    <button type="button" class="btn btn-sm btn-primary img-edit">
                        <i class="icon-pencil mr-1"></i> Edit
                    </button>
                    <button type="button" class="btn btn-sm btn-primary img-copy" data-title="Copied" data-clipboard-text="">
                        <i class="icon-copy mr-1"></i> Copy Link
                    </button>
                    <button type="button" class="btn btn-sm btn-danger img-delete">
                        <i class="icon-trash mr-1"></i> Remove
                    </button>

                </div>
            </div>

        </div>
    </div>
</div>
<!-- END Gallery Image Template -->
