<div class="row">
    <div class="col-6 offset-1">

        <form id="AOFormProfile" name="AOFormProfile" class="auto-populate" data-service="AOServiceProfile">

            <h3>Profile</h3>

            <div class="form-messages"></div>

            <input type="hidden" id="profile_image" name="profile_image" class="hide">

            <div class="form-group">
                <label for="first_name">First Name</label>
                <input type="text" id="first_name" name="first_name" class="form-control form-control-lg">
                <div class="message-container"></div>
            </div>

            <div class="form-group">
                <label for="last_name">Last Name</label>
                <input type="text" id="last_name" name="last_name" class="form-control form-control-lg">
                <div class="message-container"></div>
            </div>

            <div class="form-group">
                <label for="professional_name">Stage Name</label>
                <input type="text" id="stage_name" name="stage_name" class="form-control form-control-lg">
                <div class="message-container"></div>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" class="form-control form-control-lg">
                <div class="message-container"></div>
            </div>

            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" id="phone" name="phone" class="form-control form-control-lg">
                <div class="message-container"></div>
            </div>

            <div class="form-group">
                <label for="profile_description">Profile Description</label>
                <textarea id="profile_description" name="profile_description" class="form-control form-control-lg" rows="4" style="width: 100%;"></textarea>
                <div class="message-container"></div>
            </div>

            <div class="form-group">
                <div class="custom-control custom-switch custom-control-lg mb-1">
                    <input type="checkbox" class="custom-control-input" id="child_profile" name="child_profile" value="1">
                    <label class="custom-control-label" for="child_profile">This is a child profile.</label>
                </div>
            </div>

            <!--div class="form-group">
                <label for="password">Password</label>
                <div class="input-group">
                    <input type="password" id="password" name="password" class="form-control form-control-lg" autocomplete="new-password">
                    <span class="input-group-text input-group-append view-password">
                        <i class="icon-eye-close"></i>
                    </span>
                    <div class="message-container"></div>
                </div>
            </div -->

            <div class="form-group right">
                <button type="button" id="profile-save" class="btn btn-md theme-background"><i class="icon-save"></i>&nbsp; Save</button>
            </div>

        </form>

    </div>
</div>